### ISSUE TITLE
LXD文章其中的命令多了个冒号

### ISSUE THREAD

**Issue by tobegit3hub** [larrycai/larrycai.github.com#4]
https://github.com/larrycai/larrycai.github.com/blob/master/_posts/2015-07-14-experience-lxd-in-ustack.markdown

查看lxd镜像的命令写成了“lxc image list lxc-org:”。

**Comment by larrycai** [comment]
冒号要的 ；-）

On Thu, Jul 16, 2015 at 3:44 PM, tobe <notifications@github.com> wrote:

>
> https://github.com/larrycai/larrycai.github.com/blob/master/_posts/2015-07-14-experience-lxd-in-ustack.markdown
>
> 查看lxd镜像的命令写成了“lxc image list lxc-org:”。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larrycai/larrycai.github.com/issues/4>.
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by tobegit3hub** [comment]
我加了跑不起来，不要反而可以，确定要？

**Comment by larrycai** [comment]
https://insights.ubuntu.com/2015/04/28/getting-started-with-lxd-the-container-lightervisor/


On Thu, Jul 16, 2015 at 6:05 PM, tobe <notifications@github.com> wrote:

> 我加了跑不起来，不要反而可以，确定要？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larrycai/larrycai.github.com/issues/4#issuecomment-121915505>
> .
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)

**Comment by tobegit3hub** [comment]
好像确实是哦，有点奇怪 :)
